pipeline {
    agent any
     
    stages {
          

	stage('Set Terraform path') {
            steps {
                script {
                    def tfHome = tool name: 'Terraform'
                    env.PATH = "${tfHome}:${env.PATH}"
                }
                sh 'terraform --version'               
               
            }
        }
	    
	   
        
         stage('Initialize Terraform') {
		 steps {  
			  dir('VMInstance')
			 {
                sh 'terraform init'
			 }
		 }
	 }
		
	
	stage('Terraform Action') {
		 steps {  
			  dir('VMInstance')
			 {
		 sh 'terraform plan'		 
		 sh 'terraform $TF_ACTIONS --auto-approve'
				
			 }
		 }
	}

}
}
